### ISSUE TITLE
Update Lambda concurrency model to use event source concurrency.

### ISSUE THREAD

**Issue by sharkinsspatial** [NASA-IMPACT/hls-sentinel2-downloader-serverless#32]
Because ESA limits us to 15 concurrent download connections we currently limit download concurrency with the old style Lambda concurrency limiting approach.  Unfortunately as described in this article https://aws.amazon.com/blogs/compute/introducing-maximum-concurrency-of-aws-lambda-functions-when-using-amazon-sqs-as-an-event-source/ this approach is inefficient due to our high throttling rates.  We should migrate to using the new event source concurrency settings option.

**Comment by chuckwondo** [comment]
@sharkinsspatial, do we want to add this to our long-running `fix/esa_data_ecosystem` branch, or do we want to land that branch and open a new one for this issue?

**Comment by chuckwondo** [comment]
I created a new branch: issue32/event-source-concurrency

In order to land #33, we had to disable integration tests because deployment of the integration stack was failing, and we couldn't resolve it quickly.

With the new issue32/event-source-concurrency branch, I pushed up fixes for the integration stack deployment error, along with a fix for a failing integration test, and also re-enabled integration tests in CI.

**Comment by chuckwondo** [comment]
Since we are still using CDK v1, setting the maximum concurrency is not possible via the [v1 SqsEventSource class](https://docs.aws.amazon.com/cdk/api/v1/python/aws_cdk.aws_lambda_event_sources/SqsEventSource.html) that we are currently using. (The [v2 SqsEventSource class](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_lambda_event_sources/SqsEventSource.html) adds a `max_concurrency` parameter.)

However, it appears that we should be able to leverage the lower level [v1 CfnEventSourceMapping class](https://docs.aws.amazon.com/cdk/api/v1/python/aws_cdk.aws_lambda/CfnEventSourceMapping.html) to configure the max concurrency via the `scaling_config` parameter, so I'll attempt to replace our use of v1 SqsEventSource with v1 CfnEventSourceMapping.

**Comment by chuckwondo** [comment]
@sharkinsspatial, what do we want to set maximum concurrency to? We currently have `reserved_concurrent_executions` hard-coded to `15`. The `maximum_concurrency` for the event source concurrency must be less than the reserved concurrency. Is 10 a good number for `maximum_concurrency`?

**Comment by chuckwondo** [comment]
For your viewing pleasure, here's visual confirmation that max concurrency was set (in my integration stack):

![image](https://github.com/NASA-IMPACT/hls-sentinel2-downloader-serverless/assets/5607545/ceecd439-129c-438d-bf2d-e0bc836790c4)

**Comment by sharkinsspatial** [comment]
@chuckwondo I believe this issue with swapping event source mapping is at the Cloudformation level https://github.com/aws/aws-cdk/issues/18706.  We could jump through hoops and use a custom resource to manage the removal but in this case I would recommend a new single PR with the new event source mapping (with the maximum concurrency option) and deployment instructions to first manually remove the existing event source mapping.  We should also now be removing reserved concurrency as our only intention for using is replaced by the new max concurrency behavior.

**Comment by chuckwondo** [comment]
Makes sense. In removing the reserved concurrency limit of 15, do you want the max concurrency set to 15 instead?

**Comment by sharkinsspatial** [comment]
Let's start with 14 for initial testing.

**Comment by chuckwondo** [comment]
I opened a PR: https://github.com/NASA-IMPACT/hls-sentinel2-downloader-serverless/pull/34

I fixed the original integration tests deployment failure we were seeing before (which led to our commenting it out in order to land #33), and it [nearly deployed](https://github.com/NASA-IMPACT/hls-sentinel2-downloader-serverless/actions/runs/6880239190/job/18714085541) the integration tests stack, but it failed when attempting to deploy the DB cluster:

```plain
Cannot find version 11.15 for aurora-postgresql
```

Oddly (again), I'm able to deploy my own integration tests stack from my machine without this error (and successfully run integration tests), so it appears that there is still some lingering inconsistency between builds produced locally vs. those produced in CI.

I do recall running into this same (or similar) issue with the DB cluster while working on the updates for using the new ESA APIs, but I believe it was because we were using an obsolete version (10.7?), thus requiring the bump to the newer version because we were getting a message about not being able to find the obsolete version.

**Comment by chuckwondo** [comment]
I discovered the problem. Version 11.15 is literally no longer available:

```plain
aws rds describe-db-engine-versions --engine aurora-postgresql --query '*[].[EngineVersion]' --output text --region us-west-2
11.9
11.18
11.20
11.21
12.9
12.11
12.12
12.13
12.14
12.15
12.16
13.7
13.8
13.9
13.9
13.10
13.11
13.12
14.3
14.4
14.5
14.6
14.7
14.8
14.9
15.2
15.3
15.4
```

Unfortunately, the AWS CDK v1 for Python does not define an appropriate constant in the 11.x series beyond version 11.15 (see https://docs.aws.amazon.com/cdk/api/v1/python/aws_cdk.aws_rds/AuroraPostgresEngineVersion.html).

This is perhaps yet another motivation for upgrading to CDK v2. The v1 library is no longer being updated to match reality, so we're going to continue running into more and more of these situations.

To mitigate this, I'm going to attempt to use a version constructor because I fear that an attempt to swap out our use of the higher level `DatabaseCluster` construct for the lower level `CfnDatabaseCluster` (where we can specify the version using a string value, such as `"11.21"`) might cause the CDK to delete the existing cluster in cases where we want to update _existing_ deployments, which might end poorly.

**Comment by chuckwondo** [comment]
Regarding why my own integration tests stack successfully deployed, whereas the CI one did not, I suspect that's because when I first deployed my own stack, version 11.15 was still available, and I have not destroyed my stack since my initial deployment. So it appears that _existing_ deployments can still use that version, but new resources cannot request that version, and must instead choose a version from among those listed in my previous comment.

**Comment by chuckwondo** [comment]
@sean, deployment and execution of integration tests succeeded: https://github.com/NASA-IMPACT/hls-sentinel2-downloader-serverless/actions/runs/6896943715

PR ready for review: https://github.com/NASA-IMPACT/hls-sentinel2-downloader-serverless/pull/34

**Comment by chuckwondo** [comment]
@sharkinsspatial, can we close this now?
